### ISSUE TITLE
Guidelines for Training

### ISSUE THREAD

**Issue by thaoshibe** [dukebw/LOHO#2]
Thanks for your work!
It'd be great if you could provide guidelines for training LOHO!

**Comment by RohitSaha** [comment]
Thanks for your interest!

As an optimization framework, LOHO should take 12 minutes to generate the result. Using a CUDA enabled 16 GB GPU for the optimization process should suffice.

Additionally, LOHO uses pre-trained StyleGANv2, and other networks whose checkpoints have been added at a location for download (info in the README).

We will continue to add further details to the README but I hope the above information helps. Please let us know if there are further question.

**Comment by Eunchan24** [comment]
Thanks for your work!
I'd like to know how to train LOGO.
I'd like to run it with the data I have instead of the sample data provided, what should I do?
The code below is an error when I tried to run with the data I have.
`python loho.py --image1 00018.jpg --image2 00002.jpg --image3 00003.jpg
Traceback (most recent call last):
  File "loho.py", line 102, in <module>
    image_files['I_2_path'], image_files['M_2_path'], size=resize, normalize=1
  File "/home/eckim/code/LOHO/datasets/ffhq.py", line 88, in process_image
    mask = Image.open(mask_path).convert("RGB")
  File "/home/eckim/miniconda3/envs/loho/lib/python3.6/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/masks/00002.png'`

Thank you in advance.

**Comment by Eunchan24** [comment]
> 관심을 가져주셔서 감사합니다!
> 
> 최적화 프레임워크로서 LOHO는 결과를 생성하는 데 12분이 걸립니다. 최적화 프로세스를 위해 CUDA 지원 16GB GPU를 사용하면 충분합니다.
> 
> 또한 LOHO는 사전 훈련된 StyleGANv2 및 다운로드 위치에 체크포인트가 추가된 기타 네트워크를 사용합니다(README 정보).
> 
> 계속해서 README에 자세한 내용을 추가할 예정이지만 위의 정보가 도움이 되기를 바랍니다. 추가 질문이 있으면 알려주십시오.
Thanks for your work!
I'd like to know how to train LOGO.
I'd like to run it with the data I have instead of the sample data provided, what should I do?
The code below is an error when I tried to run with the data I have.
python loho.py --image1 00018.jpg --image2 00002.jpg --image3 00003.jpg Traceback (most recent call last): File "loho.py", line 102, in <module> image_files['I_2_path'], image_files['M_2_path'], size=resize, normalize=1 File "/home/eckim/code/LOHO/datasets/ffhq.py", line 88, in process_image mask = Image.open(mask_path).convert("RGB") File "/home/eckim/miniconda3/envs/loho/lib/python3.6/site-packages/PIL/Image.py", line 2968, in open fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: 'data/masks/00002.png'

Thank you in advance.

**Comment by Eunchan24** [comment]
> 관심을 가져주셔서 감사합니다!
> 
> 최적화 프레임워크로서 LOHO는 결과를 생성하는 데 12분이 걸립니다. 최적화 프로세스를 위해 CUDA 지원 16GB GPU를 사용하면 충분합니다.
> 
> 또한 LOHO는 사전 훈련된 StyleGANv2 및 다운로드 위치에 체크포인트가 추가된 기타 네트워크를 사용합니다(README 정보).
> 
> 계속해서 README에 자세한 내용을 추가할 예정이지만 위의 정보가 도움이 되기를 바랍니다. 추가 질문이 있으면 알려주십시오.

Thanks for your work!
I'd like to know how to train LOGO.
I'd like to run it with the data I have instead of the sample data provided, what should I do?
The code below is an error when I tried to run with the data I have.
python loho.py --image1 00018.jpg --image2 00002.jpg --image3 00003.jpg Traceback (most recent call last): File "loho.py", line 102, in <module> image_files['I_2_path'], image_files['M_2_path'], size=resize, normalize=1 File "/home/eckim/code/LOHO/datasets/ffhq.py", line 88, in process_image mask = Image.open(mask_path).convert("RGB") File "/home/eckim/miniconda3/envs/loho/lib/python3.6/site-packages/PIL/Image.py", line 2968, in open fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: 'data/masks/00002.png'

Thank you in advance.

**Comment by XYFFFFFF** [comment]
So, we didn't need to train a new model?  Cause Loho is a  optimization framework
