### ISSUE TITLE
inference.pth file corrupted ...

### ISSUE THREAD

**Issue by saakshi077** [dukebw/LOHO#3]
```
`Setting up Perceptual loss...
Loading model from: /content/LOHO/networks/lpips/weights/v0.1/vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: /content/LOHO/networks/lpips/weights/v0.1/vgg.pth
...[net-lin [vgg]] initialized
...Done
Constructing DeepLabv3+ model...
Number of classes: 20
Output stride: 16
Number of Input Channels: 3
/content/drive/MyDrive/inference.pth
Traceback (most recent call last):
  File "/content/LOHO/loho.py", line 180, in <module>
    state_dict = torch.load(graphonomy_model_path)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 1362420 more bytes. The file might be corrupted.`
```
After Executing loho.py I am getting this error.

**Comment by saakshi077** [comment]
This was a issue with google colab,  files are fine
